### PR TITLE
Vertical aspect support

### PR DESCRIPTION
**Pull request by Muzzarino**

### CODE REVIEW

**Comment by magcius** [comment]
What does this do?

**Comment by Muzzarino** [comment]
It sets the aspect ratio axis if below 16:9 by adjusting the FOV.

**Comment by magcius** [comment]
Can you give a before/after example of what this does, and what the motivation is?

**Comment by magcius** [comment]
Closing until the above is answered. Please feel free to reopen.

**Comment by Muzzarino** [comment]
If you test that code, take a screenshot of the before/after screenshots on 4:3 resolutions and you should see the differences.

**Pull request closed without merging**
